# === App Info ===
spring.application.name=com.hris.system

# === Database Configuration ===
spring.datasource.driver-class-name=org.postgresql.Driver
# URL ตรงนี้อ้างอิงจาก docker-compose ที่เราจะใช้รันกันครับ
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_db
spring.datasource.username=admin
spring.datasource.password=password123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# === File Upload Configuration ===
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
file.upload.video-dir=uploads/videos
file.upload.image-dir=uploads/images

# === Email Configuration ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pokpong.padjunreed@gmail.com
spring.mail.password=spxzeflxbtmltouz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# === 5. App Custom Properties ===
app.frontend.url=http://localhost:4200
jwt.secret=testjwtetc-must-be-at-least-32-characters-long

#sonar squ_eba17ee30a31395bed557e47315df5015978e610


